name: update sidebar
description: "update the sidebar in docsify"
inputs:
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  actor:
    description: "github.actor"
    required: true
  docs_path:
    description: "markdown documents path"
    required: true
    default: "docs"
  root_node:
    description: "root node for kg"
    required: true
    default: "root"
  push_branch:
    description: "Target branch name to push the index"
    required: true
    default: "gh-page"
  ref:
    description: "checkout-commit"
    required: true
    default: "main"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      repository: 'junxnone/autosidebar'
      path: 'script'
      ref: job2lastcommit
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.x'
      cache: 'pip'
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r script/requirements.txt
  - uses: actions/checkout@v4
    with:
      path: 'target'
      ref: ${{ inputs.ref }}
  - name: update sidebar
    shell: bash
    run: |
      cd target
      python ../script/update_sidebar.py --path "${{ inputs.docs_path }}" --repo_name "${{ github.repository }}" --rname "${{ inputs.root_node }}" | tee "${{ inputs.docs_path }}"/_sidebar.md
  - name: push to gh-page
    shell: bash
    run: |
      cd target
      REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      git config user.email "${{ inputs.actor }}@users.noreply.github.com"
      git config user.name "${{ inputs.actor }}"
      git pull ${REMOTE}
      git add ${{ inputs.docs_path }}
      git status
      git commit -am "Update _sidebar"
      echo "HEAD:${{ inputs.branch }}"
      git push ${REMOTE}  "HEAD:${{ inputs.branch }}"
