name: update sidebar
description: "update the sidebar in docsify"
inputs:
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  actor:
    description: "github.actor"
    required: true
  docs_path:
    description: "markdown documents path"
    required: true
    default: "docs"
  root_node:
    description: "root node for kg"
    required: true
    default: "root"
  push_branch:
    description: "Target branch name to push the index"
    required: true
    default: "gh-page"
runs:
  using: "composite"
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'
  - name: Set up Python package
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/junxnone/autosidebar/main/requirements.txt
      pip install -r requirements.txt
  - name: update sidebar
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/junxnone/autosidebar/main/update_sidebar.py
      python update_sidebar.py --path "${{ inputs.docs_path }}" --repo_name "${{ github.repository }}" --rname "${{ inputs.root_node }}" | tee "${{ inputs.docs_path }}"/_sidebar.md
  - name: push to gh-page
    shell: bash
    run: |
      REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      git config user.email "${{ inputs.actor }}@users.noreply.github.com"
      git config user.name "${{ inputs.actor }}"
      git pull ${REMOTE}
      git add ${{ inputs.docs_path }}
      git status
      git commit -am "Update _sidebar"
      git push ${REMOTE}  ${{ inputs.branch }}
